version: '3.6'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    volumes:
      - ./database:/var/lib/mongodb/data
      - ./data-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      retries: 5
      interval: 15s
      start_period: 30s
    networks:
      db-network:


  node-app:
    build: ./node-app
    container_name: node-app
    ports:
      - 5000:3000
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_HOST=${MONGO_HOST}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      web-network:
      db-network:


  reverse-proxy:
    build: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      web-network:
    depends_on:
      - node-app

networks:
  db-network:
    name: db-network
  web-network:
    name: web-network
